### ISSUE TITLE
[BUG] Inconsistent Username Search Result Behaviour

### ISSUE THREAD

**Issue by Hanilillicious** [kphilemon/tender#33]
Dear maintainer, 

I have tried out your application and based on my tests, I have found a weird and inconsistent username search result behavior in the discover friends page. I am not sure if this is the intended behavior and thus I am submitting this issue to raise your attention.

As you can see from the screenshot below, I have inputted `j` as my search input but the search results did not include any users with usernames that contain the character `j`.

![Screenshot_20220624_080717_com example tender (2)](https://user-images.githubusercontent.com/96814294/175436117-ed295aca-aaec-4495-84d7-e0dbeafe68c7.jpg)

**Comment by kphilemon** [comment]
Hi @Hanilillicious! Thank you for trying out the app and reaching out to us. And yes, you are right, it is indeed a bug in the search results. However, we have decided to not fix it at the moment. 

Thank you again for opening this issue. I will proceed with closing this issue if you have no other questions. Feel free to fork and add fixes to fix the bug :)
